version: '3.1'
services:
  mysql-service:
    container_name: database
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1214
      MYSQL_DATABASE: "storage"
      MYSQL_USER: "pedro"
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
  spring:
    build:
      context: .
    container_name: api
    volumes:
      - .:/app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql-service
